import FormContainer from '@component/form/FormContainer';
import FormTitle from '@component/form/FormTitle';
import { Box } from '@mui/material';
import QRCode from 'react-qr-code';
import FormTextInput from '@component/form/FormTextInput';
import FormSubmitButton from '@component/form/FormSubmitButton';
import React from 'react';
import { makeFormData } from '@hook/use-form-data';
import FormNumberInput from '@component/form/FormNumberInput';

type FormData = {
  code: string;
}

const useFormData = makeFormData<FormData>({
  code: "",
})

type ValidateTOTPFormProps = {
  url: string;
  secret: string;
  onSubmit: (code: string) => Promise<void>
}

export const ValidateTOTPForm = (props: ValidateTOTPFormProps) => {
  const { formData, makeFormChange } = useFormData();

  const handleValidate = () => props.onSubmit(formData.code);

  return (
    <FormContainer onSubmit={handleValidate}>
      <Box mb={5}>
        <FormTitle
          subtitle={"Use an authenticator app (e.g., Google Authenticator, Authy) to scan the QR code below."}
        >
          Step 1:
        </FormTitle>
        <Box display={"flex"} justifyContent={"center"}>
          <Box
            ml={2}
            my={4}
            style={{
              height: 256,
              width: 256,
            }}>
            <QRCode style={{ height: "auto", maxWidth: "100%", width: "100%" }} value={props.url}/>
          </Box>
        </Box>
        <FormTextInput label={""} subLabel={"Can’t scan? Add this key manually to the authenticator:"} value={props.secret} isReadyOnly={true}/>
      </Box>
      <Box>
        <FormTitle
          subtitle={"Enter the 6-digit code generated by your authenticator app to verify and complete the setup."}
        >
          Step 2:
        </FormTitle>
        <FormNumberInput
          label={"6-digit code"}
          value={formData.code}
          onChange={makeFormChange("code")}
          length={6}
        />
        <FormSubmitButton onClick={handleValidate}/>
      </Box>
    </FormContainer>
  )
}